### PR TITLE
Made Explorer Responsive

### PR DESCRIPTION
**Pull request by sohamb03**
Based on my previous experience in using the explorer from mobile, I decided to bring in a updates in order to make the explorer compatible. Here's a list of changes -

Made all the tables horizontally scrollable.
The graphs have been adjusted to fit in the screen without loss of quality.
Here's an example of how the explorer looks right now - https://sohamb03.me/blockchain-explorer 

*The previous one had an issue which has been fixed and for those of you who had visited the demo explorer during the previous PR, please clear your cache and then visit it again. I've had issues viewing the latest one and that's why.*

### CODE REVIEW

**Comment by brandonlehmann** [comment]
Conflicts

**Comment by brandonlehmann** [comment]
How is this better?

image

image

image

This method was avoided during the initial creation for a reason.

**Comment by sohamb03** [comment]
Well, I felt it'd be better since scrolling horizontally would've been easier than scrolling through the whole page. Personally, I'd a lot of problem doing that, and so I felt it'd be nice to keep the page integrated and only scroll through the content that needs to be rather than the whole page. 

Well, again I do understand that you might have some reason for avoiding this method. It's on you anyway.

**Comment by brandonlehmann** [comment]
> Well, I felt it'd be better since scrolling horizontally would've been easier than scrolling through the whole page. Personally, I'd a lot of problem doing that, and so I felt it'd be nice to keep the page integrated and only scroll through the content that needs to be rather than the whole page.
> 

You've hidden the vast majority of the information that is *useful* on the page on mobile. This is a step backwards in my opinion.

**Comment by brandonlehmann** [comment]
Change rejected. Please feel free to give it another go an attempt a squashed PR again.

**Comment by sohamb03** [comment]
Sure.

**Pull request closed without merging**
