### PR TITLE
Add warning for out of date nodes

### PR DESCRIPTION
**Pull request by Watt3r**
Add small warning SVG for nodes that are less than currentVersion in config.js

### CODE REVIEW

**Comment by brandonlehmann** [comment]
I’m not cool with this. Having to update that file every time someone runs a development release or otherwise is silly. Don’t compare against hard coded please. Take the highest, compare major and minor and if it’s the same it’s fine. Ignore patch version.

**Comment by Watt3r** [comment]
My bad, I agree with the patch version not being added. 

As for where we should get the version, taking the highest version from any node on the list could also be problematic, since anyone can change their node version to be highest, marking others as outdated.

Maybe it would be better to get highest node version from GitHub release tags?

**Comment by brandonlehmann** [comment]
That’s better... but still causes a problem if someone is running a newer dev version that would be labeled out of date and thus incorrect.

**Comment by Watt3r** [comment]
This PR is closed because there will be no more updates after v1.0.0, making this irrelevant.

**Pull request closed without merging**
